apiVersion: v1
kind: Service
metadata:
  name: eas-service
  labels:
    name: eas
spec:
  selector:
    name: eas
  type: "NodePort"
#  clusterIP: 10.0.0.111
#  externalIPs:
#  - "138.201.40.82"
  ports:
  - protocol: "TCP"
    port: 6001
    targetPort: 4001
    nodePort: 30401
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: eas-api-rc
  labels:
    name: eas
spec:
  replicas: 3
  selector:
    name: eas
  template:
    metadata:
      labels:
        name: eas
    spec:
      containers:
      - name: eas-api-pod
        image: index.docker.io/robbilie/eas:full
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "API"
        - name: APP_PORT
          value: "4001"
        ports:
        - containerPort: 4001
          protocol: "TCP"
      volumes:
      - name: config
        secret:
          secretName: eas-config