apiVersion: v1
kind: Service
metadata:
  name: eas-service
  labels:
    name: eas
spec:
  selector:
    name: eas
  type: "NodePort"
  ports:
  - port: 4001
    name: eas-api-rc
  - port: 4002
    name: eas-ws-rc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eas-api-rc
  labels:
    name: eas
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: eas
    spec:
      containers:
      - name: eas-api-pod
        image: index.docker.io/robbilie/eas:full
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "API"
        - name: APP_PORT
          value: "4001"
        ports:
        - containerPort: 4001
          protocol: "TCP"
      volumes:
      - name: config
        secret:
          secretName: eas-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eas-ws-rc
  labels:
    name: eas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: eas
    spec:
      containers:
      - name: eas-ws-pod
        image: index.docker.io/robbilie/eas:full
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "WS"
        - name: APP_PORT
          value: "4002"
        ports:
        - containerPort: 4002
          protocol: "TCP"
      volumes:
      - name: config
        secret:
          secretName: eas-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eas-worker-rc
  labels:
    name: eas
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: eas
    spec:
      containers:
      - name: eas-worker-pod
        image: index.docker.io/robbilie/eas:full
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "Worker"
        ports:
      volumes:
      - name: config
        secret:
          secretName: eas-config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eas-fetcher-rc
  labels:
    name: eas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: eas
    spec:
      containers:
      - name: eas-fetcher-pod
        image: index.docker.io/robbilie/eas:full
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "Fetcher"
        ports:
      volumes:
      - name: config
        secret:
          secretName: eas-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  - hosts:
    - api.utils.space
      secretName: eas-api-tls
    - ws.utils.space
      secretName: eas-ws-tls
  rules:
  - host: api.utils.space
    http:
      paths:
      - backend:
          serviceName: eas-service
          servicePort: 4001
  - host: ws.utils.space
    http:
      paths:
      - backend:
          serviceName: eas-service
          servicePort: 4002