---
kind: Service
apiVersion: v1
metadata:
  name: eas-api-service
  labels:
    app: eas-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4001
    protocol: TCP
  selector:
    app: eas-api
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: eas-api
  name: eas-api-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eas-api
  template:
    metadata:
      labels:
        app: eas-api
    spec:
      containers:
      - name: eas-api-pod
        image: robbilie/space.utils-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        resources:
          limits:
            memory: "200Mi"
            cpu: "70m"
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "API"
        - name: APP_PORT
          value: "4001"
        - name: HOST
          value: "utils.space"
        - name: UA
          value: "utils.space-eas-node.js-kubernetes-api (Robert Schuh/Vincent Eneticum)"
        - name: TASKOPLOG_URL
          value: "ws://eas-taskoplog-service"
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"
        - name: MONGO_DB
          value: "test"
        - name: XML_URL
          value: "https://api.eveonline.com"
        - name: CREST_URL
          value: "https://crest-tq.eveonline.com"
        - name: IMAGE_URL
          value: "https://imageserver.eveonline.com"
        - name: LOGIN_URL
          value: "https://login.eveonline.com"
        - name: ESI_URL
          value: "https://esi.tech.ccp.is/latest/swagger.json"
        - name: INFLUXDB_HOST
          value: "monitoring-influxdb.kube-system"
        - name: GRAPHITE_HOST
          value: "graphite-service"
        - name: UV_THREADPOOL_SIZE
          value: "128"
        - name: PARALLEL_TASK_LIMIT
          value: "20"
        readinessProbe:
          httpGet:
            path: /api-docs
            port: 4001
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /alliances/434243723/ # C C P Alliance
            port: 4001
          initialDelaySeconds: 60
          timeoutSeconds: 60
      volumes:
      - name: config
        secret:
          secretName: eas-config
      nodeSelector:
        kubernetes.io/hostname: "sheliak"
