---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: eas-worker
  name: eas-worker-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eas-worker
  template:
    metadata:
      labels:
        app: eas-worker
    spec:
      containers:
      - name: eas-worker-pod
        image: index.docker.io/robbilie/eas:eas-node
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "Worker"
        - name: HOST
          value: "utils.space"
        - name: UA
          value: "utils.space-eas-node.js-kubernetes-worker (Robert Schuh/Vincent Eneticum)"
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"
        - name: MONGO_DB
          value: "test"
        - name: XML_URL
          value: "https://api.eveonline.com"
        - name: CREST_URL
          value: "https://crest-tq.eveonline.com"
        - name: IMAGE_URL
          value: "https://imageserver.eveonline.com"
        - name: LOGIN_URL
          value: "https://login.eveonline.com"
        - name: ESI_URL
          value: "https://esi.tech.ccp.is/latest/swagger.json"
        - name: UV_THREADPOOL_SIZE
          value: "128"
        - name: PARALLEL_TASK_LIMIT
          value: "1024"
      volumes:
      - name: config
        secret:
          secretName: eas-config
      imagePullSecrets:
      - name: myregistrykey