---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: eas-worker
  name: eas-worker-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eas-worker
  template:
    metadata:
      labels:
        app: eas-worker
    spec:
      containers:
      - name: eas-worker-pod
        image: index.docker.io/robbilie/eas:eas-node
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        resources:
          limits:
            memory: "250Mi"
            #cpu: "60m"
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "Worker"
        - name: APP_PORT
          value: "4001"
        - name: HOST
          value: "utils.space"
        - name: UA
          value: "utils.space-eas-node.js-kubernetes-worker (Robert Schuh/Vincent Eneticum)"
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"
        - name: MONGO_DB
          value: "test"
        - name: INFLUXDB_HOST
          value: "monitoring-influxdb.kube-system"
        - name: GRAPHITE_HOST
          value: "graphite-service"
        - name: GO_H2_PROXY_HOST
          value: "go-swagger-http-worker-service"
        - name: GO_H2_PROXY_PORT
          value: "50051"
        - name: XML_URL
          value: "https://api.eveonline.com"
        - name: CREST_URL
          value: "https://crest-tq.eveonline.com"
        - name: IMAGE_URL
          value: "https://imageserver.eveonline.com"
        - name: LOGIN_URL
          value: "https://login.eveonline.com"
        #- name: ESI_URL
        #  value: "https://esi.tech.ccp.is/_latest/swagger.json"
        - name: UV_THREADPOOL_SIZE
          value: "128"
        - name: PARALLEL_TASK_LIMIT
          value: "50"
        - name: TASK_TIMEOUT_SECONDS
          value: "300"
        - name: REFERENCE_QUEUE_MAX
          value: "500"
        #- name: EXTENDED_METRICS
        #  value: "true"
        readinessProbe:
          httpGet:
            path: /ping
            port: 4001
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 4001
          initialDelaySeconds: 60
          timeoutSeconds: 60
      volumes:
      - name: config
        secret:
          secretName: eas-config
      nodeSelector:
        kubernetes.io/hostname: "menkar"
      imagePullSecrets:
      - name: myregistrykey